#!/bin/sh

songname=$(basename "$(mpc current | sed "-e s/ /_/g" )" | sed -e "s/_/ /g" -e "s/.mp3//g")
playpause=$(mpc status | head -2 | tail -1 | sed -e 's/\s.*$//')

if [ "$playpause" = "[paused]" ]; then
  status=" "
else
  status=" "
fi

echo "$status $songname"
